# Generated by Django 5.2.3 on 2025-07-20 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcos', '0001_initial'),
        ('network', '0002_isp'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='lco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_olts', to='lcos.lco'),
        ),
    ]
