# Generated by Django 5.2.3 on 2025-08-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_isp_created_by_isp_updated_by_olt_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='isp',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
