 @baseUrl = http://localhost:8000/api/ticket/


###############################################
# 1. PUBLIC WEBSITE – CREATE TICKET (NO AUTH)
###############################################

POST {{baseUrl}}public/
Content-Type: application/json

{
  "category": "connection",
  "notes": "Internet disconnecting frequently.",
  "name": "Arun Kumar",
  "phone": "9876543210",
  "address": "Aluva, Kochi"
}



###############################################
# 2. LCO APP – CREATE TICKET (AUTH REQUIRED)
###############################################

POST {{baseUrl}}lco/
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5NTE0MTAxLCJpYXQiOjE3Njk0OTI1MDEsImp0aSI6ImE2NWQ0NzIwNTIxMDQwZTlhZmI0NTY3NDU5NjYwODAwIiwidXNlcl9pZCI6Mn0.A_m4O9u_XvEXP4EnDERv2ofSQOihLF3VHpSCP-Wu89s

{
  "category": "topup",
  "notes": "Customer requires urgent top-up",
  "priority": "high",
  "name": "Rahul Kumar",
  "phone": "9876543210",
  "address": "Kakkanad, Kochi"
}




###############################################
# 3. ADMIN – LIST ALL TICKETS
###############################################

GET {{baseUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5NTE5MzI0LCJpYXQiOjE3Njk0OTc3MjQsImp0aSI6IjkwMDBhYmM1ZTU2OTQ3NDg4MjYxODM4ODFkNzdiMzM5IiwidXNlcl9pZCI6MX0.kywKestPYmVpKC6AVUMHNW5olt5tBswfRMsWDZIIqVU
###dasboard count for ticket
GET {{baseUrl}}admin/dashboard/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5NTE5MzI0LCJpYXQiOjE3Njk0OTc3MjQsImp0aSI6IjkwMDBhYmM1ZTU2OTQ3NDg4MjYxODM4ODFkNzdiMzM5IiwidXNlcl9pZCI6MX0.kywKestPYmVpKC6AVUMHNW5olt5tBswfRMsWDZIIqVU



###############################################
# 4. ADMIN – RETRIEVE TICKET DETAILS
###############################################

GET {{baseUrl}}1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0ODU2NDYzLCJpYXQiOjE3NjQ4MzQ4NjMsImp0aSI6IjYyMDBmYzg2ZDM0MTQ4YTM4OGQ0NmM5MWRmOTY2Njg1IiwidXNlcl9pZCI6MX0.TJln4r0Uz6IkmmO9phfdISdsH71hFNv9ACE4uznVbKg



###############################################
# 5. ADMIN – UPDATE TICKET (STATUS + REPLY)
###############################################

PATCH {{baseUrl}}1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0ODU2NDYzLCJpYXQiOjE3NjQ4MzQ4NjMsImp0aSI6IjYyMDBmYzg2ZDM0MTQ4YTM4OGQ0NmM5MWRmOTY2Njg1IiwidXNlcl9pZCI6MX0.TJln4r0Uz6IkmmO9phfdISdsH71hFNv9ACE4uznVbKg

{
  "status": "resolved",
  "reply": "Issue fixed. Please check now."
}



###############################################
# 6. ADMIN – DELETE TICKET
###############################################

DELETE {{baseUrl}}1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0ODU2NDYzLCJpYXQiOjE3NjQ4MzQ4NjMsImp0aSI6IjYyMDBmYzg2ZDM0MTQ4YTM4OGQ0NmM5MWRmOTY2Njg1IiwidXNlcl9pZCI6MX0.TJln4r0Uz6IkmmO9phfdISdsH71hFNv9ACE4uznVbKg



# filter by category,status
###
GET {{baseUrl}}?status=open&category=topup
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0ODU2NDYzLCJpYXQiOjE3NjQ4MzQ4NjMsImp0aSI6IjYyMDBmYzg2ZDM0MTQ4YTM4OGQ0NmM5MWRmOTY2Njg1IiwidXNlcl9pZCI6MX0.TJln4r0Uz6IkmmO9phfdISdsH71hFNv9ACE4uznVbKg


###############################################
# 8 .Lco – LIST TICKETS CREATED BY LCO
###############################################

GET  {{baseUrl}}list/lco/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5NTE0MTAxLCJpYXQiOjE3Njk0OTI1MDEsImp0aSI6ImE2NWQ0NzIwNTIxMDQwZTlhZmI0NTY3NDU5NjYwODAwIiwidXNlcl9pZCI6Mn0.A_m4O9u_XvEXP4EnDERv2ofSQOihLF3VHpSCP-Wu89s

