#------------------------------------------------------ website
###grtting public isps
GET http://localhost:8000/api/network/public/isps


### Search LCO by address
GET http://127.0.0.1:8000/api/lcos/public/?search=682030
Accept: application/json

###nearby lcos
### Nearby LCOs within 5 KM
GET http://127.0.0.1:8000/api/lcos/public/nearby/?lat=10.0159&lon=76.3419&radius=5
Accept: application/json



### get onu,customer details for a given olt  
GET https://api.aluvabroadband.com/api/network/olt/2/customers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczODMxOTYxLCJpYXQiOjE3NzM4MTAzNjIsImp0aSI6Ijk1MzIwMjM1MTFjNTRhYzE5NjQ0ZGUwMjRkODZlNzEyIiwidXNlcl9pZCI6IjMwIn0.cnqEyrnMlxXK94ZS7lnlWvN3SYzt_IQ0qu3Fphzypus


