# Generated by Django 5.2.3 on 2025-07-02 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0002_isp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('olts', models.ManyToManyField(related_name='lcos', to='network.olt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lco_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
