# Generated by Django 5.2.3 on 2025-07-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lco',
            name='olts',
        ),
    ]
