# Generated by Django 5.2.3 on 2025-08-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcos', '0003_lco_created_by_lco_updated_by_alter_lco_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lco',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
