# Generated by Django 5.2.3 on 2025-08-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcos', '0004_lco_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lco',
            name='networking_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
