# Generated by Django 5.2.3 on 2025-08-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcos', '0005_lco_networking_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lco',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='lco',
            name='lco_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
