# Generated by Django 5.2.3 on 2025-07-02 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lcos', '0001_initial'),
        ('network', '0002_isp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='customer_profiles/')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('lco_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_id', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('v_lan', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('ont_number', models.CharField(max_length=100)),
                ('signal', models.CharField(max_length=50)),
                ('kseb_post', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=50)),
                ('distance', models.FloatField(help_text='Distance in meters')),
                ('isp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.isp')),
                ('lco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lcos.lco')),
                ('olt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.olt')),
            ],
        ),
    ]
