### Register Super Admin

@baseUrl = http://178.248.112.16:8000/api/auth
# @baseUrl = http://localhost:8000/api/auth

POST {{baseUrl}}/register-superadmin/
Content-Type: application/json

{
  "username": "abc3",
  "email": "nisna@gmail.com",
  "phone": "9999999292",
  "password": "123"
}


### ✅ Login (Obtain Access & Refresh Tokens)---for lco
POST {{baseUrl}}/login/
Content-Type: application/json

{
  "email": "a11@gmail.com",
  "password": "Password@123"
}

### ✅ Login (Obtain Access & Refresh Tokens)---for admin
POST {{baseUrl}}/login/
Content-Type: application/json

{
  "email": "nisna@gmail.com",
  "password": "123"
}

### 🔁 Refresh Access Token
POST {{baseUrl}}/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MzQxNDk3MCwiaWF0IjoxNzUzMzI4NTcwLCJqdGkiOiI4YjMyYTJjNDdlNmY0NTM1YWRjNzRmNjVkNmM2ODFmZiIsInVzZXJfaWQiOjF9.sVvTOsc8yXjpoYdIv-KcK5qWvw_4Vb0U7qGI1kUeCGQ"
}

### 🚪 Logout (Blacklist Refresh Token)
POST {{baseUrl}}/logout/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzNDIxNDkxLCJpYXQiOjE3NTM0MTc4OTEsImp0aSI6IjllYTVkNTgxZDkxMDQyOWQ5YzkzNGE2N2Y0M2YwYmVhIiwidXNlcl9pZCI6MX0.OsMdtD7wfmguvOqVJqmBQS8g7P0_tN0lhF9t964yct8
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MzUwNDI5MSwiaWF0IjoxNzUzNDE3ODkxLCJqdGkiOiJjNmI4NTFmYmJjNzQ0ZjVkYjQxMzg2MThmNDg2ODUxNyIsInVzZXJfaWQiOjF9.utZwUQU8rCQ4fAh2Uf9agGZ80XYNY63xa6PNDo_NXiY"

}









# --------------------FORGOT PASSWORD--------------



### Send OTP
POST {{baseUrl}}/forgot-password/send-otp/
Content-Type: application/json

{
  "email": "abcd@gmail.com"
}

### Verify OTP
POST {{baseUrl}}/forgot-password/verify-otp/
Content-Type: application/json

{
  "email": "abcd@gmail.com",
  "otp": "477360"
}

### Reset Password
POST {{baseUrl}}/forgot-password/reset-password/
Content-Type: application/json

{
  "email": "abcd@gmail.com",
  "new_password": "123",
  "confirm_password": "123"
}



# -------------------SWITCH---------------------------------


### Create a Switch
POST http://localhost:8000/api/network/switches/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzY4MjAzLCJpYXQiOjE3NTEzNjQ2MDMsImp0aSI6IjgxNjVkNmMwZTk2MzRhZmM5YTAwNjU0NmVlYjUwYmRjIiwidXNlcl9pZCI6Mn0.-zf10_MszPPnhUEEoWIegKepyqw2XjSGYStyMusxWjE

{
  "name": "Main Switch02",
  "uid": "SW002",
  "make": "Cisco",
  "model_number": "X500",
  "serial_number": "SN123456",
  "package_date": "2025-07-02"
}

### List Switches
GET http://localhost:8000/api/network/switches/?page=1&page_size=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzMDM2MjM2LCJpYXQiOjE3NTMwMzI2MzYsImp0aSI6IjVlNDlkNzFjOTNjZDRlYTViMzBkOTUwZGZiMGNiZTQ1IiwidXNlcl9pZCI6Mn0.QSNlS_vB6_83EPK1GkFgjPdHRcHHvCB0uBP0x1hfsF4
### Retrieve Switch
GET http://localhost:8000/api/network/switches/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzU5MzIyLCJpYXQiOjE3NTEzNTU3MjIsImp0aSI6Ijg3NmRlMDhjZTg4ZDQ0MGQ5MzExZmVhZjc4MTlkMzhlIiwidXNlcl9pZCI6Mn0.5d95FKrV8IJWbrPspYTOFSYvhf5d1ZJGCm7z2649ZPA

### Update Switch
PUT http://localhost:8000/api/network/switches/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzU5MzIyLCJpYXQiOjE3NTEzNTU3MjIsImp0aSI6Ijg3NmRlMDhjZTg4ZDQ0MGQ5MzExZmVhZjc4MTlkMzhlIiwidXNlcl9pZCI6Mn0.5d95FKrV8IJWbrPspYTOFSYvhf5d1ZJGCm7z2649ZPA

{
  "name": "Main Switch Updated",
  "uid": "SW001",
  "make": "Cisco",
  "model_number": "X600",
  "serial_number": "SN654321",
  "package_date": "2025-07-01"
}

### Delete Switch
DELETE http://localhost:8000/api/network/switches/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzU5MzIyLCJpYXQiOjE3NTEzNTU3MjIsImp0aSI6Ijg3NmRlMDhjZTg4ZDQ0MGQ5MzExZmVhZjc4MTlkMzhlIiwidXNlcl9pZCI6Mn0.5d95FKrV8IJWbrPspYTOFSYvhf5d1ZJGCm7z2649ZPA


# -------------OLT----------------

### Create OLT
POST http://localhost:8000/api/network/olts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzY4MjAzLCJpYXQiOjE3NTEzNjQ2MDMsImp0aSI6IjgxNjVkNmMwZTk2MzRhZmM5YTAwNjU0NmVlYjUwYmRjIiwidXNlcl9pZCI6Mn0.-zf10_MszPPnhUEEoWIegKepyqw2XjSGYStyMusxWjE

{
  "name": "OLT 3",
  "uid": "OLT003",
  "make": "Huawei",
  "model_number": "HUA-OLT-1000",
  "serial_number": "SN1234567890",
  "package_date": "2025-07-01",
  "switch": 2   
}

### List OLTs
GET http://localhost:8000/api/network/olts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzMDMyNTY2LCJpYXQiOjE3NTMwMjg5NjYsImp0aSI6IjZkZGMzMThiZWU4MDQ2YzJhY2ZjNDQ4MjdlZjY0ZmJiIiwidXNlcl9pZCI6Mn0.DAxnKN1zQX5wJt-Goi5a3SCxxKZmxc8wTnXU3TiWOu8

### Retrieve OLT
GET http://localhost:8000/api/network/olts/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzY4MjAzLCJpYXQiOjE3NTEzNjQ2MDMsImp0aSI6IjgxNjVkNmMwZTk2MzRhZmM5YTAwNjU0NmVlYjUwYmRjIiwidXNlcl9pZCI6Mn0.-zf10_MszPPnhUEEoWIegKepyqw2XjSGYStyMusxWjE

### Update OLT
PUT http://localhost:8000/api/network/olts/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzY4MjAzLCJpYXQiOjE3NTEzNjQ2MDMsImp0aSI6IjgxNjVkNmMwZTk2MzRhZmM5YTAwNjU0NmVlYjUwYmRjIiwidXNlcl9pZCI6Mn0.-zf10_MszPPnhUEEoWIegKepyqw2XjSGYStyMusxWjE

{
  "name": "OLT 1 Updated",
  "uid": "OLT001",
  "make": "Huawei",
  "model_number": "HUA-OLT-2000",
  "serial_number": "SN9876543210",
  "package_date": "2025-07-01",
  "switch": 1
}

### Delete OLT
DELETE http://localhost:8000/api/network/olts/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzY4MjAzLCJpYXQiOjE3NTEzNjQ2MDMsImp0aSI6IjgxNjVkNmMwZTk2MzRhZmM5YTAwNjU0NmVlYjUwYmRjIiwidXNlcl9pZCI6Mn0.-zf10_MszPPnhUEEoWIegKepyqw2XjSGYStyMusxWjE

###un assigned olt
GET http://localhost:8000/api/network/unassigned-olts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzMDMyNTY2LCJpYXQiOjE3NTMwMjg5NjYsImp0aSI6IjZkZGMzMThiZWU4MDQ2YzJhY2ZjNDQ4MjdlZjY0ZmJiIiwidXNlcl9pZCI6Mn0.DAxnKN1zQX5wJt-Goi5a3SCxxKZmxc8wTnXU3TiWOu8


# ----------------------------ISP---------------------------------------

### Create ISP
POST http://localhost:8000/api/network/isp/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzcyODM3LCJpYXQiOjE3NTEzNjkyMzcsImp0aSI6ImE2MjYzNDBlMjI4YzQzZTQ4M2QxM2Q1ODZmYzM4ZGNkIiwidXNlcl9pZCI6Mn0.Aml5ofyH_RScsBKkul4HaVbgA5Dz2a6Mcqf0R3mHuos

{
  "name": "stampede",
  "address": "123 Fiber Road, Kochi"
}

### List All ISPs
GET http://localhost:8000/api/network/isp/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzcyODM3LCJpYXQiOjE3NTEzNjkyMzcsImp0aSI6ImE2MjYzNDBlMjI4YzQzZTQ4M2QxM2Q1ODZmYzM4ZGNkIiwidXNlcl9pZCI6Mn0.Aml5ofyH_RScsBKkul4HaVbgA5Dz2a6Mcqf0R3mHuos

### Retrieve ISP
GET http://localhost:8000/api/network/isp/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzcyODM3LCJpYXQiOjE3NTEzNjkyMzcsImp0aSI6ImE2MjYzNDBlMjI4YzQzZTQ4M2QxM2Q1ODZmYzM4ZGNkIiwidXNlcl9pZCI6Mn0.Aml5ofyH_RScsBKkul4HaVbgA5Dz2a6Mcqf0R3mHuos

### Update ISP
PUT http://localhost:8000/api/network/isp/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzcyODM3LCJpYXQiOjE3NTEzNjkyMzcsImp0aSI6ImE2MjYzNDBlMjI4YzQzZTQ4M2QxM2Q1ODZmYzM4ZGNkIiwidXNlcl9pZCI6Mn0.Aml5ofyH_RScsBKkul4HaVbgA5Dz2a6Mcqf0R3mHuos

{
  "name": "Updated ISP Name",
  "address": "Updated ISP Address"
}

### Delete ISP
DELETE http://localhost:8000/api/network/isp/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzcyODM3LCJpYXQiOjE3NTEzNjkyMzcsImp0aSI6ImE2MjYzNDBlMjI4YzQzZTQ4M2QxM2Q1ODZmYzM4ZGNkIiwidXNlcl9pZCI6Mn0.Aml5ofyH_RScsBKkul4HaVbgA5Dz2a6Mcqf0R3mHuos


# --------------LCO---------------------------------

### Create LCO (POST)
POST http://localhost:8000/api/lcos/lco/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzMDk1NTQ2LCJpYXQiOjE3NTMwOTE5NDYsImp0aSI6IjE0YTczMzhiNTg4YTQ2ZmZiMDU0OGQ0NzVhMGU3ZjU2IiwidXNlcl9pZCI6Mn0.4IeNaE-_42EJk41lzLIbngaU-y97hF1eujwPM1RMQGU

{
  "name": "jesna LCO",
  "address": "123 Main Street, Kerala",
  "aadhaar_number": "900772789012",
  "phone": "9876543225",
  "email": "abcd@gmail.com",
  "olts": [4]
}

### List LCOs (GET)
GET http://localhost:8000/api/lcos/lco/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzMDMyNTY2LCJpYXQiOjE3NTMwMjg5NjYsImp0aSI6IjZkZGMzMThiZWU4MDQ2YzJhY2ZjNDQ4MjdlZjY0ZmJiIiwidXNlcl9pZCI6Mn0.DAxnKN1zQX5wJt-Goi5a3SCxxKZmxc8wTnXU3TiWOu8

### Retrieve LCO (GET, PUT, DELETE)
GET http://localhost:8000/api/lcos/lco/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNDQwNjQ0LCJpYXQiOjE3NTE0MzcwNDQsImp0aSI6IjgxMDRhZDhiMzYzMzQzNTNiZGUzMmMxNzhmMDM4ODE5IiwidXNlcl9pZCI6Mn0.pnkgsiJjaMCwaX99MWwJDNq95cU-PP-YfL1FOuuAlC4

### Update LCO (GET, PUT, DELETE)
GET http://localhost:8000/api/lcos/lco/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNDQwNjQ0LCJpYXQiOjE3NTE0MzcwNDQsImp0aSI6IjgxMDRhZDhiMzYzMzQzNTNiZGUzMmMxNzhmMDM4ODE5IiwidXNlcl9pZCI6Mn0.pnkgsiJjaMCwaX99MWwJDNq95cU-PP-YfL1FOuuAlC4

### Delete LCO (GET, PUT, DELETE)
GET http://localhost:8000/api/lcos/lco/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNDQwNjQ0LCJpYXQiOjE3NTE0MzcwNDQsImp0aSI6IjgxMDRhZDhiMzYzMzQzNTNiZGUzMmMxNzhmMDM4ODE5IiwidXNlcl9pZCI6Mn0.pnkgsiJjaMCwaX99MWwJDNq95cU-PP-YfL1FOuuAlC4


# ---------CUSTOMER----------

### List all customers (with search and pagination)
GET http://localhost:8000/api/client/customer/?search=&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0NDY2MTM2LCJpYXQiOjE3NTQ0NjI1MzYsImp0aSI6IjQzNzAzYmU0NjgwMTQ1MDJiYmVkMjVkOTUxYjc2YjMyIiwidXNlcl9pZCI6Mn0.rJD3inUr2CLs_bq-HNjVz9nx0ZA-G7YJz-d_CZi-dQg


### Create customer
POST http://localhost:8000/api/client/customer/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyOTE1ODI2LCJpYXQiOjE3NTI5MTIyMjYsImp0aSI6IjI4ZDVmNDQ1N2Q3YTQ4ZTFiODFjNDYyNjBlNTEwZjEzIiwidXNlcl9pZCI6Mn0.c4LUschf1YIeOFY2b3exva8ZwmVmnHAVD1TRR2Ikti0

{
  "full_name": "John Doe",
  "phone": "9876843210",
  "address": "123 Street",
  "email": "johgn@example.com",
  "mac_id": "00:1B:44:11:3A:B7",
  "plan": "Premium 100Mbps",
  "v_lan": "200",
  "lco": 1,
  "lco_ref": "LCO123",
  "isp": 1,
  "expiry_date": "2025-08-01",
  "ont_number": "ONT56789",
  "olt": 2,
  "signal": "-20 dBm",
  "kseb_post": "KP-40",
  "port": "PON1",
  "distance": 200.5
}

### Get single customer
GET http://localhost:8000/api/client/customer/13/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzMTY1MjcxLCJpYXQiOjE3NTMxNjE2NzEsImp0aSI6ImNiZGZmYTE0Mjg0NTQ3NGU4NTZhYzJkZTkxOTk2ZTY4IiwidXNlcl9pZCI6Mn0.Wms2KNfdI10Ak3bkoQ9jcy6bEkd1V-IgLWgWwlNuRA0

### Update customer
PUT http://localhost:8000/api/client/customer/1/
Content-Type: application/json

{
  "full_name": "John Updated",
  "phone": "9876543210",
  ...
}

### Delete customer
DELETE http://localhost:8000/api/client/customer/1/


### plan expiring soon customer 
GET http://localhost:8000/api/client/expiring-soon/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0NDgwNjkwLCJpYXQiOjE3NTQ0NzcwOTAsImp0aSI6Ijg2NjJlZWMwNWJlZjQ1MWRiZWY1MTE0ZjdiOWJiM2RhIiwidXNlcl9pZCI6MX0.PKqt4Orn1t1HKPzsBIVuM0CEV8qiW_I-nywB3VpU1H0



# bulk upload


# ------------REPORT 

### Search all customers with "baker" in any searchable field
GET http://localhost:8000/api/client/search/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzMTc4MDU4LCJpYXQiOjE3NTMxNzQ0NTgsImp0aSI6ImJiNDRlY2U2YTU5YzQ3ZjBhOWFiYmM3NGY0NmRiNTRmIiwidXNlcl9pZCI6Mn0.GaRp7YbADBUJILK2a80qHovl-NRWvnP3qgfwcmn6Y-w
###

### Filter by OLT, LCO, and ISP
GET http://localhost:8000/api/client/search/?olt=2&lco=1&isp=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzNzc0NzgzLCJpYXQiOjE3NTM3NzExODMsImp0aSI6IjBjZDVlNWYxYmY0YTQzZjRhYmZhMTMxYWEyMTg0OGY2IiwidXNlcl9pZCI6MX0.br4Bx2wSiGrva4a1v81oxR-OjdbYff7ezxFuEy8clYI

# report generation

### Generate Excel report with selected fields
POST http://localhost:8000/api/client/report/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNDU4MjY5LCJpYXQiOjE3NTE0NTQ2NjksImp0aSI6IjQ5YzQzOTg1YjI1MzQ4OGFiZjViY2VkMDllNmMzNDk5IiwidXNlcl9pZCI6Mn0.5edLRg0IOVYXT_n_dMy3d3N8We-K1ggaRU8Rssw3_Tw

{
  "fields": ["email", "expiry_date", "plan", "mac_id"]
}


###dashboard
GET http://localhost:8000/api/client/counts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzMjQ1NTY4LCJpYXQiOjE3NTMyNDE5NjgsImp0aSI6IjJkODQwMGFkYTAxZTQ2ZjE4MzQ4YTc5YWYzZTJmMzRkIiwidXNlcl9pZCI6Mn0.RH87zzyeI72PXi135gdRQGdIA9cMZwCKp6659uk_o_4






# ====================MOBILE APPLICATION-----------------------------

### ✅ Login LCO
POST {{baseUrl}}/login/
Content-Type: application/json

{
  "email": "abcd@gmail.com",
  "password": "b2cCFwSV"
}


### change password
POST http://localhost:8000/api/auth/change-password/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNTIxOTAzLCJpYXQiOjE3NTE1MTgzMDMsImp0aSI6ImMxNTEwZjk0Yjg1NjRkODA5ODM3OGQwYWI3NTg0MDA3IiwidXNlcl9pZCI6N30.j-uTqHuCnb7vwGwHSWC1AwIvHOw9333WiUr4SqJQ7xw

{
  "old_password": "ZKqkNIdE",
  "new_password": "123",
  "confirm_password": "123"
}


# LCO customer list 

### Get customers for logged-in LCO (search by name or phone, filtered by ISP/OLT)
GET http://localhost:8000/api/client/my-customers/search/?search=John&isp=3&olt=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNTIxOTAzLCJpYXQiOjE3NTE1MTgzMDMsImp0aSI6ImMxNTEwZjk0Yjg1NjRkODA5ODM3OGQwYWI3NTg0MDA3IiwidXNlcl9pZCI6N30.j-uTqHuCnb7vwGwHSWC1AwIvHOw9333WiUr4SqJQ7xw
